apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-collector-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics-collector
  template:
    metadata:
      labels:
        app: statistics-collector
    spec:
      containers:
      - name: statistics-collector
        image: khoribz/statistics_collector:latest
        ports:
        - containerPort: 8080
        env:
          - name: APP_HOST
            value: "app-service"
          - name: APP_PORT
            value: "80"
