apiVersion: v1
kind: Service
metadata:
  name: statistics-collector-service
spec:
  selector:
    app: statistics-collector
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
